name: Auto deploy
on:
  workflow_call:
jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "test" 
