name: Vue Build
on:
  workflow_call:
jobs:
  vue-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        npm run build --if-present
    - name: Commit output
      uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: "Build: ({sha}) {msg}"
        branch: "${GITHUB_REF#refs/heads/}"
